version: '3.8'

services:
  telegram-bot:
    container_name: telegram_bot
    build: .
    networks:
      - app-network

  postgres:
    container_name: postgres_db
    image: postgres:latest
    environment:
      POSTGRES_DB: cp
      POSTGRES_USER: main
      POSTGRES_PASSWORD: Azamat2341!
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - app-network
    ports:
      - "5432:5432"  # Expose PostgreSQL port 5432 to the host on the same port

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
